### PR TITLE
Revert "[PyTorch] Set and override shape API for NDArray"

### PR DESCRIPTION
**Pull request by frankfliu**
Reverts deepjavalibrary/djl#958

### CODE REVIEW

**Comment by frankfliu** [comment]
integration test failed:
```
    [ERROR] - Test ai.djl.integration.tests.ndarray.NDArrayOtherOpTest.testSetWithShape FAILED
    [ERROR] - 
    java.lang.AssertionError: expected [ND: (2, 2) cpu() float32
    [[9., 8.],
     [7., 6.],
    ]
    ] but found [ND: (1, 2) cpu() float32
    [[9., 8.],
    ]
    ]
```

And it also cause other failure:
```
    [DEBUG] - cannot perform reduction function argmax on a tensor with no elements because the operation does not have an identity
    Exception raised from argmax_out at ../aten/src/ATen/native/ReduceOps.cpp:1027 (most recent call first):
    frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 98 (0x11589ae52 in libc10.dylib)
    frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 106 (0x115899d1a in libc10.dylib)
    frame #2: at::native::argmax_out(at::Tensor&, at::Tensor const&, c10::optional<long long>, bool) + 1889 (0x131e7f481 in libtorch_cpu.dylib)
    frame #3: at::native::argmax(at::Tensor const&, c10::optional<long long>, bool) + 134 (0x131e7fad6 in libtorch_cpu.dylib)
    frame #4: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, c10::optional<long long>, bool), &(at::(anonymous namespace)::(anonymous namespace)::wrapper_argmax(at::Tensor const&, c10::optional<long long>, bool))>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, c10::optional<long long>, bool> >, at::Tensor (at::Tensor const&, c10::optional<long long>, bool)>::call(c10::OperatorKernel*, at::Tensor const&, c10::optional<long long>, bool) + 25 (0x1324f3d59 in libtorch_cpu.dylib)
    frame #5: at::Tensor c10::Dispatcher::call<at::Tensor, at::Tensor const&, c10::optional<long long>, bool>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, c10::optional<long long>, bool)> const&, at::Tensor const&, c10::optional<long long>, bool) const + 215 (0x13233a527 in libtorch_cpu.dylib)
    frame #6: at::argmax(at::Tensor const&, c10::optional<long long>, bool) + 95 (0x1322256af in libtorch_cpu.dylib)
    frame #7: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, c10::optional<long long>, bool), &(torch::autograd::VariableType::(anonymous namespace)::argmax(at::Tensor const&, c10::optional<long long>, bool))>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, c10::optional<long long>, bool> >, at::Tensor (at::Tensor const&, c10::optional<long long>, bool)>::call(c10::OperatorKernel*, at::Tensor const&, c10::optional<long long>, bool) + 89 (0x133d97259 in libtorch_cpu.dylib)
    frame #8: at::Tensor c10::Dispatcher::call<at::Tensor, at::Tensor const&, c10::optional<long long>, bool>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, c10::optional<long long>, bool)> const&, at::Tensor const&, c10::optional<long long>, bool) const + 215 (0x13233a527 in libtorch_cpu.dylib)
    frame #9: at::Tensor::argmax(c10::optional<long long>, bool) const + 95 (0x1327a26cf in libtorch_cpu.dylib)
    frame #10: Java_ai_djl_pytorch_jni_PyTorchLibrary_torchArgMax__JJZ + 184 (0x13191b278 in 0.12.0-SNAPSHOT-cpu-libdjl_torch.dy)
    frame #11: 0x0 + 4658751079 (0x115aee667 in ???)
```

**Comment by stu1130** [comment]
Is it flaky? Why didn't we capture it when we run the test

**Comment by stu1130** [comment]
The argmax error is fine as it tested the exception case

**Comment by frankfliu** [comment]
> Is it flaky? Why didn't we capture it when we run the test? The argmax error is fine as it tested the exception case

No, it's not flaky. I don't know why it passed to PR check.

The bug is:
1. in PtNDArray, it caches the shape, so the check failed. I tried to fix the shape cache, it still fail. It seems native Tensor also remembers the shape. And getItem() call fail.

I don't it make sense to change NDArray Shape after created. I have a fix to address large buffer size issue. I can create a PR after this reverted.

**Review by stu1130 — APPROVED** [review]

**Comment by zachgk** [comment]
FYI @zemei

**Comment by zemei** [comment]
The `testSetWithShape` integration test is new and had the same failure until I built and manually copied the JNI library for PyTorch.

Does it require some extra steps when the JNI library changed?

**Pull request merged**
